-- 09 Monastic life + events: availability rules + resolver priority + board/coarse privacy, invitations (HC, human confirm,
-- calendar effects, privacy), events (permissions, readiness, volunteers, public listing), monastic score (cap, self-created).
do $$
declare A constant uuid := 'aaaaaaaa-0000-0000-0000-000000000001';
  ABBOT uuid := test.pid('abbot'); DEP uuid := test.pid('deputy_abbot'); BHI uuid := test.pid('bhikkhu'); SAM uuid := test.pid('samanera');
  SEC uuid := test.pid('monk_secretary'); CM uuid := test.pid('community_member'); VOL uuid := test.pid('volunteer');
  STF uuid := test.pid('staff_general'); FM uuid := test.pid('facility_manager'); VIS uuid := test.pid('visiting_monastic');
  r uuid; inv uuid; inv2 uuid; ev uuid; tv uuid; tm uuid; q uuid; qa uuid; part uuid; ver int; n bigint; ok boolean; st text; j jsonb; i int;
  t0 timestamptz := date_trunc('hour', now()) + interval '2 days 3 hours';
begin
  -- ===== availability =====
  perform test.as_person(BHI);
  ok := false; begin perform app.set_availability(A, BHI, 'AVAILABLE', null, null, null); exception when check_violation then ok := true; end;
  perform test.assert(ok, 'valid_until required (server never defaults)');
  ok := false; begin perform app.set_availability(A, BHI, 'AVAILABLE', null, now() + interval '30 hours', null); exception when check_violation then ok := true; end;
  perform test.assert(ok, 'AVAILABLE max 24h');
  ok := false; begin perform app.set_availability(A, BHI, 'CEREMONY', null, now() + interval '1 hour', null); exception when invalid_parameter_value then ok := true; end;
  perform test.assert(ok, 'calendar state not settable');
  perform app.set_availability(A, BHI, 'AVAILABLE', null, now() + interval '2 hours', null);
  select state into st from app.my_availability(A); perform test.assert(st = 'AVAILABLE', 'self AVAILABLE resolves, got ' || st);
  ok := false; begin insert into public.availability_manual(temple_id, person_id, state, valid_until, set_by_person_id) values (A, BHI, 'REST', now() + interval '1 hour', BHI);
    exception when insufficient_privilege then ok := true; end;
  perform test.assert(ok, 'no direct insert into availability_manual');
  ok := false; begin perform * from app.availability_board(A); exception when insufficient_privilege then ok := true; end;
  perform test.assert(ok, 'bhikkhu (scope C) cannot read the full board');
  reset role;

  perform test.as_person(SEC);
  ok := false; begin perform app.set_availability(A, BHI, 'REST', null, now() + interval '3 hours', null); exception when insufficient_privilege then ok := true; end;
  perform test.assert(ok, 'others may set UNAVAILABLE only');
  perform app.set_availability(A, BHI, 'UNAVAILABLE', null, now() + interval '3 days', 'SICK');
  select state into st from app.availability_board(A) b where b.person_id = BHI and b.reason = 'MANUAL:SICK';
  perform test.assert(st = 'UNAVAILABLE', 'manual UNAVAILABLE beats AVAILABLE');
  select count(*) into n from app.availability_board(A) b where b.person_id = CM; perform test.assert(n = 0, 'board lists monastics only');
  reset role;
  perform test.as_person(BHI);
  select count(*) into n from app.availability_coarse(A) c where c.person_id = BHI and c.coarse = 'BUSY';
  perform test.assert(n = 1, 'coarse view shows BUSY without reason');
  reset role;
  perform test.as_person(CM);
  ok := false; begin perform * from app.availability_coarse(A); exception when insufficient_privilege then ok := true; end;
  perform test.assert(ok, 'community member cannot see monk availability');
  ok := false; begin perform app.set_availability(A, CM, 'AVAILABLE', null, now() + interval '1 hour', null); exception when invalid_parameter_value then ok := true; end;
  perform test.assert(ok, 'lay person has no availability');
  reset role;
  -- calendar priority: ceremony now beats manual AVAILABLE; no signal => UNKNOWN; check-in => IN_TEMPLE
  insert into public.schedule_entries(temple_id, kind, title, person_id, starts_at, ends_at, created_by, venue_kind)
  values (A, 'ceremony', 'พิธีทดสอบ', DEP, now() - interval '10 minutes', now() + interval '50 minutes', SEC, 'IN_TEMPLE');
  perform test.as_person(DEP); perform app.set_availability(A, DEP, 'AVAILABLE', null, now() + interval '1 hour', null);
  select state into st from app.my_availability(A); perform test.assert(st = 'CEREMONY', 'calendar CEREMONY beats manual AVAILABLE, got ' || st); reset role;
  select state into st from app.resolve_availability(A, VIS, now()); perform test.assert(st = 'UNKNOWN', 'no signal => UNKNOWN, never AVAILABLE');
  perform test.as_person(VIS); perform app.check_in(A); select state into st from app.my_availability(A); reset role;
  perform test.assert(st = 'IN_TEMPLE', 'fresh check-in => IN_TEMPLE');
  ok := false; begin insert into public.schedule_entries(temple_id, kind, title, person_id, starts_at, ends_at, created_by, venue_kind, source_type, source_id)
    values (A, 'invitation', 'x', DEP, now(), now() + interval '1 hour', SEC, 'OFF_SITE', 'invitation', gen_random_uuid()); exception when insufficient_privilege then ok := true; end;
  perform test.assert(ok, 'source-owned schedule rows cannot be written directly');

  -- ===== invitations =====
  perform test.as_person(BHI);
  ok := false; begin perform app.save_rite_type(A, 'สวดมนต์', true, false, 60); exception when insufficient_privilege then ok := true; end;
  perform test.assert(ok, 'bhikkhu cannot manage rite types');
  reset role;
  perform test.as_person(SEC);
  r := app.save_rite_type(A, 'สวดมนต์เย็น (ทดสอบ)', true, false, 60);
  inv := app.create_invitation(A, 'เจ้าภาพทดสอบ', '0800000001', 'ญาติ', r, 'บ้านทดสอบ (สมมติ)', t0, 60, 2, 'HOST_PROVIDES', 30, 30, 'phone', null);
  ver := app.invitation_transition(A, inv, 1, 'start_review');
  reset role;
  perform test.as_person(DEP); perform app.set_availability(A, DEP, 'AVAILABLE', t0 - interval '1 hour', t0 + interval '3 hours', null); reset role;
  perform test.as_person(SEC);
  select list into st from app.suggest_team(A, inv) s where s.person_id = DEP; perform test.assert(st = 'suggested', 'opted-in monk suggested, got ' || st);
  select list into st from app.suggest_team(A, inv) s where s.person_id = ABBOT; perform test.assert(st = 'needs_confirmation', 'no signal => needs_confirmation');
  select array_to_string(violations, ',') into st from app.suggest_team(A, inv) s where s.person_id = BHI;
  perform test.assert(st = 'MANUAL_BLOCK', 'manual block excludes (HC-2), got ' || coalesce(st, 'null'));
  select array_to_string(violations, ',') into st from app.suggest_team(A, inv) s where s.person_id = SAM;
  perform test.assert(st = 'NOT_ELIGIBLE', 'samanera not eligible by default (HC-1)');
  select person_id into r from app.suggest_team(A, inv) limit 1; perform test.assert(r = DEP, 'opted-in list always first');
  ok := false; begin perform app.invitation_transition(A, inv, ver, 'propose_team', array[DEP, BHI]); exception when check_violation then ok := true; end;
  perform test.assert(ok, 'hard constraint cannot be overridden by propose_team');
  ver := app.invitation_transition(A, inv, ver, 'propose_team', array[DEP, ABBOT]);
  ok := false; begin perform app.invitation_transition(A, inv, ver, 'confirm', null, null, null, true); exception when insufficient_privilege then ok := true; end;
  perform test.assert(ok, 'secretary (delegated only) cannot confirm without delegation');
  reset role;
  perform test.as_person(ABBOT);
  ok := false; begin perform app.invitation_transition(A, inv, ver - 1, 'confirm', null, null, null, true); exception when serialization_failure then ok := true; end;
  perform test.assert(ok, 'stale version refused');
  ok := false; begin perform app.invitation_transition(A, inv, ver, 'confirm'); exception when check_violation then ok := true; end;
  perform test.assert(ok, 'warnings (NO_AVAILABILITY_SIGNAL) must be acknowledged');
  ver := app.invitation_transition(A, inv, ver, 'confirm', null, null, null, true);
  reset role;
  select count(*) into n from public.schedule_entries where source_type = 'invitation' and source_id = inv and venue_kind = 'OFF_SITE';
  perform test.assert(n = 6, 'confirm writes OUT/invitation/BACK rows per monk, got ' || n);
  select state into st from app.resolve_availability(A, DEP, t0 + interval '10 minutes'); perform test.assert(st = 'ON_INVITATION', 'during rite => ON_INVITATION');
  select state into st from app.resolve_availability(A, DEP, t0 - interval '10 minutes'); perform test.assert(st = 'TRAVELING', 'before rite => TRAVELING');
  perform test.as_person(BHI);
  select count(*) into n from public.invitations where id = inv; perform test.assert(n = 0, 'bhikkhu (scope A) cannot see invitations he is not on');
  ok := false; begin perform app.invitation_respond(A, inv, 'ACKNOWLEDGED'); exception when insufficient_privilege then ok := true; end;
  perform test.assert(ok, 'non-team monk cannot respond');
  reset role;
  perform test.as_person(DEP);
  perform app.invitation_respond(A, inv, 'ACKNOWLEDGED');
  reset role;
  perform test.as_person(CM);
  select count(*) into n from public.invitations; perform test.assert(n = 0, 'lay member cannot see invitations (host data)');
  reset role;
  perform test.as_person(SEC);
  inv2 := app.create_invitation(A, 'เจ้าภาพสอง', null, null, (select id from public.rite_types where name_th like 'สวดมนต์เย็น%'), 'ที่สมมติ', t0 + interval '30 minutes', 60, 1, 'OTHER', null, null, 'line', null);
  select array_to_string(violations, ',') into st from app.suggest_team(A, inv2) s where s.person_id = DEP;
  perform test.assert(st like '%COMMITMENT_OVERLAP%', 'confirmed invitation blocks overlapping one (HC-3), got ' || coalesce(st, 'null'));
  select count(*) into n from app.suggest_team(A, inv2) s where 'RETURN_BUFFER_UNKNOWN' = any (s.warnings);
  perform test.assert(n > 0, 'unknown travel => RETURN_BUFFER_UNKNOWN warning');
  reset role;
  perform test.as_person(ABBOT);
  ok := false; begin perform app.invitation_transition(A, inv, ver, 'cancel', null, null, ' '); exception when check_violation then ok := true; end;
  perform test.assert(ok, 'cancel needs a reason');
  ver := app.invitation_transition(A, inv, ver, 'cancel', null, null, 'เจ้าภาพยกเลิก (ทดสอบ)');
  reset role;
  select count(*) into n from public.schedule_entries where source_id = inv and status = 'CANCELLED'; perform test.assert(n = 6, 'cancel cancels calendar rows');
  select state into st from app.resolve_availability(A, DEP, t0 + interval '10 minutes'); perform test.assert(st <> 'ON_INVITATION', 'cancelled rows no longer count');

  -- ===== events =====
  perform test.as_person(CM);
  ok := false; begin perform app.save_event(A, null, 'community', 'งานทดสอบ', null, now() + interval '10 days', now() + interval '10 days 3 hours', 'ลานวัด', 'public', null, 100);
    exception when insufficient_privilege then ok := true; end;
  perform test.assert(ok, 'community member cannot create events');
  reset role;
  perform test.as_person(SEC);
  ev := app.save_event(A, null, 'merit_offering', 'งานบุญทดสอบ', 'รายละเอียดสมมติ', now() + interval '10 days', now() + interval '10 days 3 hours', 'ลานวัด (สมมติ)', 'public', null, 100);
  ok := false; begin perform app.event_transition(A, ev, 'plan'); exception when check_violation then ok := true; end;
  perform test.assert(ok, 'plan needs a lead person');
  perform app.save_event(A, ev, 'merit_offering', 'งานบุญทดสอบ', 'รายละเอียดสมมติ', now() + interval '10 days', now() + interval '10 days 3 hours', 'ลานวัด (สมมติ)', 'public', SEC, 100);
  perform app.event_transition(A, ev, 'plan');
  tv := app.save_staffing_target(A, ev, 'volunteer', 'อาสาจัดสถานที่', 2, null, true);
  tm := app.save_staffing_target(A, ev, 'monk', 'พระสวด', 1, null, true);
  ok := false; begin perform app.add_event_participant(A, tm, STF); exception when check_violation then ok := true; end;
  perform test.assert(ok, 'lay person cannot fill a monk slot');
  perform app.add_event_participant(A, tm, DEP);
  q := app.add_event_task(A, ev, 'เตรียมเครื่องเสียง', 3, false, now() + interval '9 days', STF);
  j := app.event_readiness(A, ev);
  perform test.assert(j->>'state' = 'NOT_READY' and j->'gates'->>'G-STAFF' = 'FAIL', 'unfilled hard volunteer target => NOT_READY, got ' || j::text);
  perform test.assert((j->>'percent')::int = 24, 'readiness percent = floor(100*(0.6*0+0.4*0.6)) = 24, got ' || (j->>'percent'));
  ok := false; begin perform app.event_transition(A, ev, 'approve'); exception when insufficient_privilege then ok := true; end;
  perform test.assert(ok, 'approve needs event.approve (secretary only delegated)');
  reset role;
  select count(*) into n from public.schedule_entries where source_type = 'event' and source_id = ev and person_id = DEP;
  perform test.assert(n = 1, 'monk added to event gets a ceremony calendar row');
  perform test.as_person(ABBOT); perform app.event_transition(A, ev, 'approve'); reset role;

  perform test.as_person(CM); perform app.volunteer_signup(A, tv);
  j := app.event_readiness(A, ev);
  perform test.assert(j ? 'state' and not (j ? 'gates'), 'community member sees only state + percent, got ' || coalesce(j::text, 'null'));
  ok := false; begin perform app.decide_participant(A, (select id from public.event_participants where person_id = CM), true); exception when insufficient_privilege then ok := true; end;
  perform test.assert(ok, 'volunteer cannot approve own sign-up');
  reset role;
  perform test.as_person(VOL); perform app.volunteer_signup(A, tv); reset role;
  perform test.as_person(SAM);
  ok := false; begin perform app.volunteer_signup(A, tv); exception when insufficient_privilege then ok := true; end;
  perform test.assert(ok, 'monastic cannot sign up as lay volunteer');
  reset role;
  perform test.as_person(FM);
  for part in select id from public.event_participants where target_id = tv and status = 'PENDING' loop perform app.decide_participant(A, part, true); end loop;
  reset role;
  -- task flow: assignee submits, a different person with event.manage verifies
  select id into qa from public.quest_assignments where quest_id = q;
  perform test.as_person(STF);
  perform app.event_task_progress(A, qa, 'start'); perform app.event_task_progress(A, qa, 'submit');
  ok := false; begin perform app.event_task_progress(A, qa, 'verify'); exception when insufficient_privilege then ok := true; end;
  perform test.assert(ok, 'assignee cannot verify own task');
  reset role;
  perform test.as_person(SEC);
  perform app.event_task_progress(A, qa, 'verify');
  j := app.event_readiness(A, ev);
  perform test.assert(j->>'state' = 'READY' and (j->>'percent')::int = 100, 'all done + staffed => READY 100, got ' || j::text);
  reset role;
  perform set_config('request.jwt.claims', '', false); execute 'set role anon';
  select count(*) into n from public.temple_public_events('demo-a') e where e.id = ev and e.volunteers_needed = 0;
  perform test.assert(n = 1, 'public event listed for visitors with volunteers still needed');
  reset role;
  perform test.as_person((select id from public.persons where display_name = 'b_owner'));
  perform test.assert(app.event_readiness(A, ev) is null, 'other temple gets nothing');
  select count(*) into n from public.events where id = ev; perform test.assert(n = 0, 'other temple cannot read event');
  reset role;
  perform test.as_person(SEC);
  perform app.save_event(A, null, 'other', 'ประชุมภายในทดสอบ', null, now() + interval '5 days', now() + interval '5 days 1 hour', 'กุฏิ', 'internal', SEC, null);
  perform app.save_event(A, ev, 'merit_offering', 'งานบุญทดสอบ', 'รายละเอียดสมมติ', now() + interval '11 days', now() + interval '11 days 3 hours', 'ลานวัด (สมมติ)', 'public', SEC, 100);
  ok := false; begin perform app.event_transition(A, ev, 'cancel', 'ทดสอบ'); exception when insufficient_privilege then ok := true; end;
  perform test.assert(ok, 'cancelling an APPROVED event needs event.approve');
  reset role;
  select count(*) into n from public.event_participants where event_id = ev and status = 'PENDING';
  perform test.assert(n = 3, 'reschedule => confirmed participants must reconfirm, got ' || n);
  perform test.as_person(CM);
  select count(*) into n from public.events where visibility = 'internal'; perform test.assert(n = 0, 'internal events hidden from community members');
  reset role;
  perform test.as_person(STF);
  select count(*) into n from public.events where visibility = 'internal'; perform test.assert(n = 0, 'internal events hidden from staff with event.view T but no event.manage');
  select count(*) into n from public.events where id = ev; perform test.assert(n = 1, 'staff with event.view T sees temple events');
  reset role;
  perform test.as_person(FM);
  perform app.volunteer_signup(A, tv);
  ok := false; begin perform app.decide_participant(A, (select id from public.event_participants where person_id = FM and target_id = tv), true);
    exception when no_data_found then ok := true; end;
  perform test.assert(ok, 'volunteer approver cannot approve own sign-up');
  reset role;

  -- ===== monastic activity score =====
  for i in 1..4 loop
    insert into public.quests(temple_id, quest_type, title, created_by, status, verification_policy, points)
    values (A, 'monastic_daily', 'กิจวัตรทดสอบ ' || i, SEC, 'OPEN', 'staff_verification', 10) returning id into q;
    insert into public.quest_assignments(temple_id, quest_id, assignee_person_id) values (A, q, BHI) returning id into qa;
    perform test.as_person(BHI);
    update public.quest_assignments set status = 'IN_PROGRESS' where id = qa; update public.quest_assignments set status = 'SUBMITTED' where id = qa;
    reset role;
    perform test.as_person(SEC);
    update public.quest_assignments set status = 'COMPLETED', verifier_person_id = SEC where id = qa;
    reset role;
  end loop;
  select coalesce(sum(amount), 0) into n from public.monastic_activity_ledger where temple_id = A and person_id = BHI;
  perform test.assert(n = 30, 'daily cap 30 (4 x 10 points => 30), got ' || n);
  -- self-created quest earns 0 (checked on a monk far below the cap); a normal quest for the same monk earns its points
  for i in 1..2 loop
    insert into public.quests(temple_id, quest_type, title, created_by, status, verification_policy, points)
    values (A, 'monastic_daily', 'กิจทดสอบ ' || i, case i when 1 then VIS else SEC end, 'OPEN', 'staff_verification', case i when 1 then 10 else 5 end) returning id into q;
    insert into public.quest_assignments(temple_id, quest_id, assignee_person_id) values (A, q, VIS) returning id into qa;
    perform test.as_person(VIS);
    update public.quest_assignments set status = 'IN_PROGRESS' where id = qa; update public.quest_assignments set status = 'SUBMITTED' where id = qa;
    reset role;
    perform test.as_person(SEC); update public.quest_assignments set status = 'COMPLETED', verifier_person_id = SEC where id = qa; reset role;
  end loop;
  select coalesce(sum(amount), 0) into n from public.monastic_activity_ledger where temple_id = A and person_id = VIS;
  perform test.assert(n = 5, 'self-created quest earns 0, other quest earns 5, got ' || n);
  select count(*) into n from public.audit_logs where action = 'scoring.award_capped'; perform test.assert(n >= 1, 'capped award audited');
  perform test.as_person(ABBOT);
  select count(*) into n from public.monastic_activity_ledger where person_id = BHI; perform test.assert(n = 0, 'abbot cannot see a monk''s score');
  reset role;
  perform test.as_person(BHI);
  select practice_days_this_month, activity_score into n, i from app.my_practice(A);
  perform test.assert(n = 1 and i = 30, 'practice days + own score visible to the monk');
  select count(*) into n from app.my_day(A, (now() at time zone 'Asia/Bangkok')::date) d where d.item_kind = 'quest';
  perform test.assert(n >= 4, 'My Day lists today''s quests');
  reset role;
  perform test.as_person(CM);
  select count(*) into n from app.my_practice(A); perform test.assert(n = 0, 'lay person has no monastic practice view');
  reset role;
  raise notice 'PASS 09_monastic_events: availability, resolver, privacy, invitations (HC + human confirm), events/readiness/volunteers, monastic score';
end $$;
