#!/usr/bin/env python3
"""Generate supabase/seed/001_roles_permissions.sql from docs/master/role_permissions.yaml.
Usage: python3 supabase/seed/gen_roles_seed.py [--check]   (--check: exit 1 if the .sql is stale)
Expands @groups, explicit role keys override group values, "-" removes a grant."""
import re, sys
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "docs/master/role_permissions.yaml"
OUT = Path(__file__).resolve().parent / "001_roles_permissions.sql"
RANK = {"S": 1, "A": 1, "P": 1, "C": 1, "D": 2, "T": 3}
VAL = re.compile(r"^([SDTACP](?:\+[SDTACP])?)(?:\((\w+)\))?$")

def q(s):
    return "'" + s.replace("'", "''") + "'"

def main():
    d = yaml.safe_load(SRC.read_text(encoding="utf-8"))
    groups = d["groups"]
    def expand(k, seen=()):
        if not k.startswith("@"):
            return [k]
        out = []
        for m in groups[k]:
            out += expand(m)
        return out
    roles = d["modes"]["monastic"] + d["modes"]["community_staff"]
    lines = ["-- GENERATED by supabase/seed/gen_roles_seed.py from docs/master/role_permissions.yaml. Do not edit.",
             "begin;"]
    for mode in ("monastic", "community_staff"):
        for r in d["modes"][mode]:
            lines.append(f"insert into public.roles(code, mode) values ({q(r)}, {q(mode)});")
    restricted = set(d.get("restricted", []))
    rows = []
    for perm, spec in d["grants"].items():
        eff = {}
        for k, v in spec.items():
            if k.startswith("@"):
                for r in expand(k):
                    eff.setdefault(r, v)
        for k, v in spec.items():
            if not k.startswith("@"):
                eff[k] = v
        lines.append(f"insert into public.permissions(code, restricted) values ({q(perm)}, {str(perm in restricted).lower()});")
        for r, v in sorted(eff.items()):
            if v == "-":
                continue
            assert r in roles, (perm, r)
            m = VAL.match(str(v))
            assert m, (perm, r, v)
            sc, cond = m.group(1), m.group(2)
            rank = max(RANK[c] for c in sc.split("+"))
            rows.append(f"({q(r)}, {q(perm)}, {q(sc)}, {rank}, {q(cond) if cond else 'null'})")
    lines.append("insert into public.role_permissions(role_code, permission_code, scope, scope_rank, condition) values")
    lines.append(",\n".join(rows) + ";")
    lines.append("commit;")
    text = "\n".join(lines) + "\n"
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text() == text else 1)
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(rows)} grants, {len(roles)} roles)")

main()
